name: nailfit
version: 0.8.0+9
publish_to: 'none'

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
