name: aims_flow_scanner
version: 1.5.2+18
publish_to: 'none'

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/mobile_preview/
